# Generated by Django 5.1.2 on 2024-11-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='empleado',
            new_name='id_empleado',
        ),
    ]
